// Updated At: 2026-05-05 11:20:00
// ============================================
// STRICT PROJECT DATA - DO NOT HALLUCINATE
// ============================================

export const PROJECTS = {
  "greenairy": {
    projectName: "Chandak Greenairy",
    configurations: {
      "1 BHK": {
        sizes: [444, 463, 476],
        unit: "sq ft",
      },
      "2 BHK": {
        sizes: [661, 667, 669, 683],
        unit: "sq ft",
      },
      "3 BHK": {
        sizes: [899, 1146, 1152],
        unit: "sq ft",
      },
      "4 BHK": {
        sizes: [1327, 1346, 1378],
        unit: "sq ft",
      },
    },
    usp: [
      "Prime location with excellent connectivity",
      "Strategic location advantage",
      "Superior connectivity to major hubs",
    ],
    commonObjections: [
      "Pricing compared to competitors",
      "Value for money concerns",
      "Competitor offerings at lower price points",
    ],
    faqs: [
      { q: "What is the total Size of Land Parcel", a: "Total land parcel is 3.9 acres including sale, rehab & sai saptarshi society" },
      { q: "How much square feet of land is Sale component land parcel", a: "Sale plot area is approx 2.3 acres (1,00,190 sq ft)" },
      { q: "Size of land parcel used for Construction of sale Building and dimensions", a: "The shape is not purely rectangular. For sale it is 160m frontage and 57m depth of plot, approximately" },
      { q: "Size of total open to sky area in the land parcel of sale", a: "Commercial plaza approximately 25000 sqft, Residential Drop off & driveways-28500 sqft, Podium Terrace-23000 sqft" },
      { q: "Total no of flats for sale", a: "Total 788 nos in two towers. 394 nos in one tower" },
      { q: "Total squarefeet for sale", a: "RERA residential- 4,40,676 sq ft. RERA commercial & retail- 1,69,000 sq ft" },
      { q: "Rehab land parcel size", a: "1.6 acres" },
      { q: "Total number of rehab flats", a: "Rehab residential- 850 nos. Rehab commercial-141. Religious structure - 3nos. Sai saptarshi society flats- 83 flats. Sai saptarshi commercial-18nos" },
      { q: "Total Hutments that were there", a: "934 nos. (commercial & residential total) slums of siddharth nagar & ganesh nagar. Sai saptarshi society 1& 2, 83 flats & 18 nos shops (this is not slum)" },
      { q: "where will be the access road for existing tenants", a: "Independent access from 18.3m wide road on eastern side of the plot. However, for emergency purposes, fire tender movement is permitted from the sale plot" },
      { q: "what is the Height and view of Rehab building", a: "95mts. 2basement+G+31. They do not overlook on sale. Their views towards 18.3m wide road & magathane depot" },
      { q: "Whats the Land title (SRA, MHADA, Lease - if lease then the type and years)", a: "MHADA & BEST ( It’s a MHADA Land being developed under SRA scheme)" },
      { q: "Dimensions of the land and what is the frontage", a: "The shape is not purely rectangular. Approximately it is 160m frontage for sale and 57m depth" },
      { q: "Size, number and positioning of gates for entry and exit", a: "2nos entry/exits for Sale residential. Towards northwest & southwest corner of plot. Entry & Exit for sale commercial is from the commercial plaza on the western expressway" },
      { q: "where is the Pedistrain entry and exit and its size", a: "Near residential entry/exits" },
      { q: "where is the Access for commercial & Residential", a: "From Western express highway service road" },
      { q: "What is the Depth of Excavation", a: "12mts" },
      { q: "What is the Type of foundation", a: "Open raft" },
      { q: "Is there Shore piling or retention wall", a: "Yes" },
      { q: "What is the type of construction (Conventional or Casting)", a: "Aluform" },
      { q: "What is the Size, height & dimensions of Entrance lobby", a: "Approximate area of 40ftx30ft (Double height of 20 feet) individual for both tower." },
      { q: "What is the Seating arrangement in the entrance lobby", a: "Group seating and reception" },
      { q: "AC, Sofas and the amenities in the lobby will be provided or not", a: "Yes" },
      { q: "Is there a provision for wheelchair entry in the lobby", a: "Yes" },
      { q: "Number of Security cabins and its location", a: "2 nos. One each towards north and south entry/exit of plot" },
      { q: "What is the width of internal road for Fire vehicle", a: "9m" },
      { q: "What is the contractor name and his background", a: "H.S. Infracare" },
      { q: "Who is the consultant for amenities and his background", a: "Ingrain is the architect & Nikhil Naik will be doing the interiors" },
      { q: "Total number of car parks in the complex", a: "766 nos on podium for residential and 270 in basement for commercial & visitors" },
      { q: "Total number of visitor car park", a: "60 nos" },
      { q: "Type of car park (Puzzle/stack/tandeum/stilt)", a: "Puzzle &Stack" },
      { q: "Size of car park & weight capacity of individual slot and each puzzle", a: "2.3mX4.5m for small cars & 2.5mx5.5m for large cars. Weight-Can accommodate an SUV in larger parking space" },
      { q: "Waiting time for car park in case of puzzle", a: "Avg 1.5minute per car" },
      { q: "What is the height of boundary wall", a: "5 feet" },
      { q: "Access to car parking is via ramp or car lift", a: "Ramp" },
      { q: "Total no of basements/podiums?", a: "2nos basement for commercial parking & Residential parking podium 6 floors" },
      { q: "What is the total area of amenities", a: "Indoor Amenities of 12500 sq ft" },
      { q: "Total number of amenities", a: "20+" },
      { q: "Whether the amenities will be common in the complex or the towers will have their individual amenities", a: "Common" },
      { q: "Human capacity of the amenities like, clubhouse, community hall etc", a: "Banquet hall -150 people" },
      { q: "Depth of swimming pool and kids pool and its demensions", a: "4 feet for swimming pool. 1'6\" feet for kids pool" },
      { q: "Total amenities on rooftop", a: "12 nos." },
      { q: "What is the height of terrace wall", a: "1.5m" },
      { q: "Whether the top slab will have double casting slab as terrace will have amenities", a: "No" },
      { q: "Waterproofing provisions in the building and its service tenure", a: "Membrane waterproofing. Service tenure 10 years" },
      { q: "Total number of elevators", a: "Residential: Ground to Last residential floor- 7nos. Passenger lifts Per tower. (Out of the total passenger elevators 2nos will go till terrace.) Commercial: Basement to Tenth floor. Four elevators per tower. Service elevator: 1 service elevator for residential. Basement to Last residential floor." },
      { q: "whether the elevators will go to the terrace (if not is there a provision for wheelchair ramp)", a: "2nos elevator in each tower will go to terrace" },
      { q: "If the elevators will not go to terrace then how will the senior citizen having touble in climbing reach the rooftop", a: "(No answer provided)" },
      { q: "Whether we are providing solar pannels", a: "Yes" },
      { q: "Capacity of solar panels to generate electricity", a: "Will be provided as per norms" },
      { q: "Placement of solar panels", a: "Roof level" },
      { q: "Provision of powerback up", a: "Alternate power supply will be given" },
      { q: "Position of generators and capacity of generators", a: "(No answer provided)" },
      { q: "What is the brand of elevators", a: "Schindler or Kone or Thyssenkrup or equivalent" },
      { q: "What are the total no of elevators", a: "Refer Q .48." },
      { q: "what is the after sales service period of elevators (In years) and the cost of extending the warranty", a: "As per manufacturer" },
      { q: "What is the grade of cement used for walls and slabs", a: "Minimum OPC43" },
      { q: "Total no of Servant's toilets and their location in the complex/building", a: "1 nos. on each residential floor in each tower. On the midlanding of staircase" },
      { q: "What is the weight capacity of the service lift for carrying furniture and materials", a: "Service lift has weight capacity of 1000 kg" },
      { q: "No of refuge flats and its floors & the total area of refuge", a: "14 flats in each tower (considering G+45 floors) and one more refuge floor on 7th level which is commercial level. Residential refuge FSI area is approximately 9850 sq ft in each tower" },
      { q: "Do we have rain water harvesting? If yes then what is the storage capacity", a: "Rain water tank" },
      { q: "Do we have a Borewell", a: "No" },
      { q: "Is there a Provision for EV charging and the number of slots for the same", a: "10% of parking spaces" },
      { q: "Whats the size and brand of tiles for flooring", a: "800mmx800 mm(Subject to availability at time of execution) Simpolo/Johnson/Equivalent" },
      { q: "Size and brand of tiles for bathroom, kitchen wall, bathroom walls", a: "1 ft X2 ft tiles for kitchen. 2ft X2ft Tiles for bathroom floor & ceiling. Brands: Johnson, simpolo or equivalent" },
      { q: "Till what height are we providing dado tiles in the kitchen and washrooms", a: "All walls till lintel level in washrooms and walls adjoining kitchen platform" },
      { q: "What is the brand of sanitary and faucets", a: "Parryware" },
      { q: "Number of years warranty of faucets", a: "10 years manufacturer's warranty" },
      { q: "What is the brand of switches, ELCB and MCB", a: "Legrand or equivalent" },
      { q: "What is the brand of electric wires and the size in mm for regular switches and for AC, Geyser etc", a: "It will vary from 1.5sqmm, 2 sqmm, 2.5sqmm, depending on appliances being used inside flat. Polycab or RR kabel or KEI cable or Equivalent" },
      { q: "Position & number of switches and sockets", a: "Detailed electrical plan to be referred for this" },
      { q: "Are we providing provision for split AC in the flat (The hole for inserting the AC pipe)", a: "Yes" },
      { q: "Is there a provision for keeping the outdoor units of AC? If yes what is the position in the elevation", a: "On the chajja/toilet shaft" },
      { q: "is there Provision for drain pipe of AC so that it dosent spoil the elevation and building colour", a: "Yes" },
      { q: "Size of windows in living area, bedrooms, kitchen and washrooms", a: "Living room of 8 feet width, bedroom of 7 feet width, toilet 1'6\" width, kitchen 4' width" },
      { q: "Are we providing safety railings or half fixed windows", a: "Half fixed windows" },
      { q: "No of window tracks in rooms and kitchen", a: "Design development is in progress. Will revert on this" },
      { q: "Type of glass used in windows", a: "Single glazed clear glass" },
      { q: "Height of safety railing or half fixed windows", a: "3'3\" from floor for half fixed windows" },
      { q: "Type of paint used inside the flat and its brand", a: "Acrylic paint. Asian paints or Dulux or Equivalent" },
      { q: "Type of paint used for the building external walls and its brand. Also if it is water proof or water repellent", a: "Textured paint, water repellent. Dulux or Asian paints or equivalent" },
      { q: "what is the size of individual floor lobby", a: "Refer Answer to Q. 23" },
      { q: "What is the distance between the flat doors", a: "Refer plan" },
      { q: "Provision for sunlight and ventilation on the floors", a: "Refer plan" },
      { q: "Whether the top floors will have seprate line for water due to less pressure", a: "Yes" },
      { q: "The doors provided will be FRP or wooden", a: "Flush doors" },
      { q: "Door frames wooden or marble?", a: "Main doors wooden, Toilet doors Wooden/Granite" },
      { q: "Kitchen platform length and breadth", a: "Varies from unit to unit. Minimum 7 feet. Refer unit plans" },
      { q: "Material of kitchen platform (Name of granite)", a: "Engineered stone or Granite" },
      { q: "Base of kitchen platform will be marble or Kadappa", a: "Marble" },
      { q: "what will be the size of kitchen sink and its brand", a: "Minimum 16x19x7inch nirali or equivalent" },
      { q: "Whether there will be patti on kitchen platform to arrest water during cleaning or no", a: "Yes" },
      { q: "Whether washrooms will have concealed or open flush tanks", a: "Dual flush valve" },
      { q: "Whether the shower area will have a glass partition", a: "No" },
      { q: "Whether the shower area will have a little sunk", a: "Overall toilet area will have a tile drop" },
      { q: "Placement and provisions for Washing machine and fridge inside the flat", a: "Refer unit plans" },
      { q: "Size & dimensions of space demarcated for washing machine and fridge.", a: "2ftx2ft minimum" },
      { q: "BMC and RERA carpet areas with dimension", a: "Refer RERA sheet & stack sheet" },
      { q: "What is the structure, floor plan and total units of commercial and retail", a: "As per RERA sheet" },
      { q: "Total saleable & carpet area of commercial and retail", a: "As per RERA sheet" },
      { q: "Any certifications like IGBC for the project", a: "Yes" },
      { q: "Provider of electricity - TATA or Adani", a: "TATA/Adani" },
      { q: "Two phase or 3 phase wiring", a: "Single phase inside apartment" },
      { q: "Are we providing CPVC or PVC pipes and its brand", a: "Water supply CPVC and for drainage UPVC. Brands-Supreme or Astral or Prince or Ashirwad or equivalent" },
      { q: "What is the provision for Landline/internet/cable", a: "Conduits are laid and power points being given for internet & router. No provision of landline" },
      { q: "Are we providing lightining arrestor", a: "Yes" },
      { q: "Is the buiilding earthquake resistant? If yes then what is its standard", a: "Yes as per IS 1893" },
      { q: "What is the Sesmic zone of our project", a: "Seismic zone 3" },
      { q: "Type of internal walls plaster (Cement/POP/Neru)", a: "Gypsum plaster" },
      { q: "What is the provision for LV for fiber optics", a: "Conduit provision will be made. Fiber optics will be as per service provider." },
      { q: "RERA and developer date for possesion", a: "30-06-2028 (As per RERA sheet)" },
      { q: "window frame whether it will be granite or marble", a: "Granite" },
      { q: "Door frame whether it will be wood or marble", a: "Wood for regular doors. Granite for toilet doors" },
      { q: "What is the door lock brand", a: "Godrej or Yale equivalent" },
      { q: "Are all the apartments vastu compliance", a: "Apartment entry are vastu compliant" },
      { q: "What is the provision for two wheeler parking", a: "Two wheeler parking provision in on basement for commercial and parking podium for residential" },
      { q: "1st habital floors starts from which floor and its height", a: "12th floor. 3m Top of Slab to Top of Slab height" },
      { q: "Do we have power backup", a: "Alternate power supply will be given" },
      { q: "Size of Interenal Road", a: "9m" },
      { q: "what is the provision for drying clothes", a: "No specific area is earmarked" },
      { q: "Will there be marble or tiles in lobby", a: "Tiles" },
      { q: "Will there be anti termite treatment inside the flats or just in the building", a: "Yes" },
      { q: "Incase of ramp for car parking, size of ramp", a: "3.6m width one way" },
      { q: "Density of the project i.e apartement to land area", a: "1260 sq ft per apartment" },
      { q: "What will be size of chajja", a: "Minimum 1'6\"" },
      { q: "How deep will be the chajja from the slab", a: "2' minimum" },
      { q: "Floor to ceiling height and slab to slab height", a: "TOS to TOS is 3m. Avg slab thicknes of 150mm" },
      { q: "Is there any provision for dish washer in the kitchen.", a: "No" },
      { q: "Is Window is sound proof.", a: "Windows will be sound attenuating" },
      { q: "Are you giving modular kitchen, light, fan, bulb, gyser, Video door phone etc.", a: "No" },
      { q: "Is there will be open space for car parking", a: "No" },
      { q: "Can I buy extra car parking if yes then what is the price.", a: "Subject to availability" },
      { q: "What are the Existing litigations & their impact on project", a: "NO existing litigations" },
      { q: "Will we do the Conveyance for the land in favour of society", a: "Yes - after completion of the Development of the entire project layout" },
      { q: "Whethere the complex will have a single society or individual societies", a: "Single - as of now" },
      { q: "How much will be the property Tax", a: "As per applicable norms" },
      { q: "How much will be the maintenance after the developer exits", a: "Depends on the upkeep of the Project" },
      { q: "Will the new acquisition of 3 buildings will form a part of this project ? What will you construct there? How many teneants are there in those buildings?", a: "Will revert on the launch" },
      { q: "How many partner are there in the project and their respective role.", a: "Will revert on the launch" },
      { q: "Amenities will be maintained by even after the possession. ?", a: "FMC" },
      { q: "Can we get the fitout possessions before OC.", a: "NO" },
      { q: "Will commercial owner use amenities.", a: "NO" },
      { q: "Can the customer sell his unit before posession", a: "NO" },
      { q: "Can we visit nearby projects delivered by the company.", a: "check with the respective society" }
    ]
  },
  "sarvam": {
    projectName: "Chandak Sarvam",
    developer: "Chandak",
    location: "JB Nagar, Andheri (East), Mumbai",
    basicDetails: [
      "Land: 1.7 acres out of a 3.5 acre parcel",
      "Basements: 5 levels",
      "All buildings connected from rooftop except 2 which are individually connected",
      "Floors: Ground + 13 upper floors"
    ],
    floorBands: [
      "Floors 1–4, 5–8, 9–13",
      "Floor 13 are not currently for sale(not known to the public and will only be sold after possession for a higher price)"
    ],
    wings: {
      "Wing E (Sapphire)": [
        "Unit 1 & 2: Signature 3 BHK — 1,280 sq ft (RERA carpet 1,090 sq ft) — floors 1–12",
        "Unit 3 & 4: Royal 2 BHK — 780 sq ft (floors 1–10), 825 sq ft on 11th & 12th floors"
      ],
      "Wing F (Emerald)": [
        "Unit 1: Regal 4 BHK — 2,440 sq ft (RERA carpet 2,077 sq ft) — floors 1–12",
        "Unit 2: Signature 3 BHK — 1,280 sq ft — floors 1–12",
        "Unit 3: Royal 3 BHK — 1,260 sq ft — floors 1–12"
      ],
      "Wing C (Jade)": [
        "Units 1, 2, 3: Elite 3 BHK — 1,100 sq ft — floors 1–10",
        "Unit 4: Elite 2 BHK — 775 sq ft — floors 1–10",
        "Top floor: Pool, kids pool, steam rooms, massage room, spa area"
      ],
      "Wing D (Opal)": [
        "Unit 1: Royal 3 BHK — 1,227 sq ft — floors 1–12",
        "Unit 2: Signature 4 BHK — 1,646 sq ft — floors 1–12",
        "Unit 3: Royal 2 BHK — 780 sq ft (floors 1–10), 825 sq ft (floors 11–12)"
      ]
    },
    usp: [
      "Only branded developer with major parking space in Andheri",
      "Largest 4BHK in the micro-market",
      "Premium amenities: Gym, banquet area, private dining, party hall, guest suites, pool on top floor, spa",
      "Sales office and engineer's cabin to be handed over as Reserve Green (open green space)"
    ],
    commonObjections: [
      "Why Andheri East over other micro-markets?",
      "Justify pricing vs. competition",
      "Explain RERA carpet vs. total area to a confused buyer",
      "Positioning the 4BHK as the largest in the area",
      "Explaining the rooftop connectivity and lifestyle amenities",
      "Conversion strategy for the premium buyer segment"
    ],
    faqs: [
      { q: "Pedestrian entry and exit: Size, breadth, and location.", a: "Yes, 1.2 mtr wide." },
      { q: "Security cabins: Locations and details.", a: "1 at the entrance/ exit gate." },
      { q: "Number of gates: Size (height), location, and dimensions.", a: "1 gate for entry and exit 1.5mtr ht." },
      { q: "Height of boundary wall: Overall and between sale and tenant buildings.", a: "1.5 mtr." },
      { q: "Distance between two towers.", a: "Varies as per design." },
      { q: "Provision for wheelchair entry in the lobby.", a: "All lobbies are accessible to all." },
      { q: "Number of amenities and their total area", a: "approx 40000 sft amenities (open as well as closed amenities at ground floor and terrace)." },
      { q: "Number of amenities with size.", a: "Enclosed Amenities Total Area approx 10200 sft. Entrance lounge = 1060 sqft. Guest suite 1 = 400 sqft, Guest suite 2 = 350 sqft. Private Dining Area = 400 sqft (Excluding the Kitchen and Powder room). Celebration Hall = 1600 sqft. AV room = 360 sqft. Indoor games = 1050 sqft. Seating and meditation deck = 1860 sqft. Yoga room = 648 sqft. Fitness center = 1447 sqft. Creche = 1052 sqft. Open Amenities at ground floor Total area approx 14000 sft. Youngster Zone or kids play area. Senior citizen seating. Active lawn. Discovery garden. Sculpture garden. Water deck. Linear seating. Leisure Amphitheater. Recreational Green. Multi-use court - Space to play leisure basketball, cricket vooleyball/ trhow ball or double it as mini pickle ball court for game practice. Terrace Amenities approx area 15000 sft. infinity pool = adult pool 20'x40' kids pool 10'6\"x10'6\" and SPA. Seating plaza. hammock garden. Organic patch. Formal seating. Youth Zone. Multipurpose deck. Rejuvenation Path. Barbecue station. Socio Cultural Lawn. Biophilic garden. Sky Dining. Star gazing deck. Reflexology path. Zen Pathway. Multipurpose deck. Space for solar panels." },
      { q: "Human capacity of amenities (e.g., clubhouse, community hall).", a: "Party Hall - around 50 people , Gym - 20people at a time, AV ROOM - 10 people, yoga room 10-12 people, creche- 8-10 children." },
      { q: "Size, height, and dimensions of the entrance lobby.", a: "3.2 mtr, each looby will be spacious and well designed." },
      { q: "Seating arrangement in the entrance lobby.", a: "Yes, sofa seating." },
      { q: "Amenities in the lobby (e.g., AC, sofas).", a: "Airconditioned lobbies." },
      { q: "Capacity of solar panels to generate electricity", a: "As per IGBC norms." },
      { q: "Placement of solar panels", a: "On terrace." },
      { q: "Vermiculture", a: "No." },
      { q: "Rainwater harvesting / STP", a: "Yes, As per IGBC and MCGM norms." },
      { q: "Certifications like IGBC.", a: "Yes IGBC Certification." },
      { q: "Type of construction (Conventional, Casting, or Mivan).", a: "Alu form construction." },
      { q: "Number of basements/podiums and their use.", a: "LG and 4 basements." },
      { q: "Height of terrace wall.", a: "1.5 mtr." },
      { q: "First habitable floor: Starting height.", a: "9'0\" from road level." },
      { q: "Number of floors: Uniformity across towers.", a: "14 residential floors." },
      { q: "Floor plans and number of units per floor.", a: "Refer stack sheet shared." },
      { q: "Brand, dimensions, passenger capacity, and service period.", a: "TBD , will be a reputed brand." },
      { q: "Whether elevators go to the terrace.", a: "No." },
      { q: "Accessibility for senior citizens to the terrace if elevators don’t go.", a: "Spa and all other enclosed amenities are accessable to all. There areamenities planned for senior citizens at ground level in case there is a difficulty in climibing stairs to terrace." },
      { q: "Dedicated/express elevators for terrace amenities.", a: "To Spa and swimming pool only." },
      { q: "Service lift for carrying furniture and materials", a: "One of the lifts to be used as service lift." },
      { q: "Additional (third lift) for C wing - will it stop on every floor or only on the ground & 14th floor", a: "4th, 8th and 12th and 14th floor." },
      { q: "Total number of flats for sale and their saleable area.", a: "Wing A- 5 flats per floor, B, C, E have 4 flats per floor D, F have 3 flats per floor." },
      { q: "Planned expansions around the project.", a: "No." },
      { q: "Garbage chute availability.", a: "No." },
      { q: "Width of internal driveway for sale buildings", a: "6 mtr wide 2 way driveway." },
      { q: "Width of internal driveway for redevelopment/tenant buildings", a: "6 mtr wide 2 way driveway." },
      { q: "Any common amenities between sale buildings and tenant buildings", a: "No." },
      { q: "Exterior paint - water repellent and its warranty with brand", a: "TBD , will be a reputed brand." },
      { q: "Whether the top slab will have double casting as the terrace will have amenities", a: "Only for Swimming pool double slab construction will be done." },
      { q: "Distance between the towers including redevelopment/tenant buildings", a: "Varies." },
      { q: "Provision for sunlight and ventilation on the floors", a: "All apartment will have adequate light ventillation." },
      { q: "Type of internal wall plaster (Cement/POP/Neru/Gypsum)", a: "Gypsum plaster." },
      { q: "Size of chajja", a: "Varies as per design." },
      { q: "Depth of chajja from the slab", a: "Varies as per design." },
      { q: "Floor-to-ceiling height and slab-to-slab height", a: "2.95 mtr floor to floor height." },
      { q: "Number of staircases and their width", a: "2 Staircase in A wing, 1 staircase each in wing B-F." },
      { q: "What is the internal flooring we are offering in the flat", a: "Marble in living and dining, tiles at all other places." },
      { q: "Size and make of tiles for flooring", a: "TBD , will be a reputed brand." },
      { q: "Size and make of tiles for bathroom, kitchen wall, and bathroom walls", a: "TBD , will be a reputed brand." },
      { q: "Height of dado tiles in the kitchen and washrooms", a: "Till beam bottom." },
      { q: "Size of windows in living area, bedrooms, kitchen, and washrooms", a: "As per guidelines." },
      { q: "Provision for mosquito nets and if we are providing them", a: "No." },
      { q: "No of window tracks", a: "2 track, 3 track windows as per room size and design requirements." },
      { q: "Type of glass used in windows", a: "Clear Glass." },
      { q: "The doors provided will be FRP or wooden", a: "Laminated flush doors for flats." },
      { q: "Door frames - wooden or marble", a: "wooden for main door and bed room doors, Granite for Toilet." },
      { q: "Kitchen platform length and breadth", a: "Length Varies as per layout width will be 2'0\"." },
      { q: "Material of kitchen platform", a: "Granite." },
      { q: "Size of kitchen sink", a: "SS SINK 16\"X22\"." },
      { q: "Whether washrooms will have concealed or open flush tanks", a: "Concealed." },
      { q: "Whether the shower area will have a glass partition", a: "No." },
      { q: "Window frame - granite or marble", a: "Granite." },
      { q: "Are we giving loft in washroom?", a: "No." },
      { q: "Will there be marble or tiles in the lobby?", a: "All typical lobbies will have tiles." },
      { q: "Whether we are providing safety railing and the material used", a: "No." },
      { q: "Whether the shower area will have a tile drop between wet and dry areas", a: "Yes." },
      { q: "Water sprinklers in flats and common areas, whether covered or not", a: "Open sprinklers for fire fighting." },
      { q: "No of car parks in the complex", a: "As per MCGM norms." },
      { q: "No of visitor car parks", a: "As per MCGM norms." },
      { q: "No of 2-wheeler parking", a: "No." },
      { q: "Type of car park & size of a car park", a: "Surface Parking Big cars 2.5x5.5 mtr and small car 2.3x4.5 mtr." },
      { q: "Access to car parking via ramp or car lift if any", a: "Ramp." },
      { q: "In case of a ramp for car parking, size of ramp", a: "6mtr wide 2 way ramp." },
      { q: "Architect & Construction Partners", a: "Design Architect IAG Consultant." },
      { q: "No of refuge flats and size of a refuge area", a: "B Wing 8th floor has a refuge flat, all other refuge areas are at mid landing." },
      { q: "Are we providing a lightning arrester?", a: "As per norms." },
      { q: "Is the building earthquake-resistant? If yes, up to what magnitude on the Richter Scale", a: "yes." },
      { q: "Seismic zone of our project", a: "Zone 2/3." },
      { q: "Fire chute", a: "No." },
      { q: "Whether we are providing solar panels", a: "Yes." },
      { q: "No of charging points for EV vehicles and their positioning", a: "as per IGBC norms." },
      { q: "No of servants' toilets", a: "In Basement." },
      { q: "Any waiting lounge for drivers", a: "In Basement." },
      { q: "Borewell", a: "No." },
      { q: "Brand of sanitary and faucets", a: "Reputed brand." },
      { q: "Warranty of faucets", a: "As per brand policy." },
      { q: "Provision for AC in the flat", a: "only wiring and sleeve." },
      { q: "Provision for keeping the outdoor units of AC", a: "Yes." },
      { q: "Provision for drain pipe of AC to avoid spoiling the elevation and building color", a: "Yes." },
      { q: "Whether the top floors will have a separate water line due to less pressure", a: "MEP design will ensure all units have required pressure." },
      { q: "Provision for washing machine and fridge", a: "Yes." },
      { q: "Are we providing geyser in bathrooms? If yes, which brand", a: "Yes, Reputed Brand." },
      { q: "Two-phase or three-phase wiring", a: "As per Design requirements." },
      { q: "Provision for landline/internet/cable", a: "Provision." },
      { q: "Provision for LV for fiber optics", a: "Yes." },
      { q: "Door lock brand", a: "To be decided, Reputed brand." },
      { q: "Provision for drying clothes", a: "Utility can be used for the same." },
      { q: "Car washing area", a: "Most parkings are surface parking, for those who do not have surface parking dedicated area will be provided." },
      { q: "What is the overall project USP? What are the USPs of each individual flat?", a: "Gated community, deck in each apartment, minimum wastage in passages, well planned amenities." },
      { q: "How green is the project?", a: "kindly elaborate." },
      { q: "At what height from the sea level (altitude) is the project located?", a: "13.0mtr from MSL." },
      { q: "Total number of units?", a: "317 Units." },
      { q: "Number of towers in Rehab building", a: "4 towers." },
      { q: "Total number of units in Rehab towers", a: "340." },
      { q: "Rehab families access point", a: "Separate gate." },
      { q: "Capacity of domestic water tank", a: "As per MCGM norms." },
      { q: "Capacity of fire water tank", a: "As per MCGM norms." },
      { q: "Is there storm water management in the project? Any suction pumps?", a: "No suction Pumps." },
      { q: "Capacity of solar panels to generate electricity?", a: "As per IGBC norms." },
      { q: "Eco-friendly building technology used in the project?", a: "As per Green building norms, IGBC norms." },
      { q: "Number of towers", a: "6 towers." },
      { q: "What are the options of view from different flats and heights?", a: "Garden view ( inward looking flats) and City view." },
      { q: "What is the depth of excavation and RCC foundation?", a: "as per design requirement." },
      { q: "Distance between the flats (Adjacent and opposite units)", a: "Typical floor lobbies are approx 2 mtr wide." },
      { q: "Would the towers planned for the next set of launches hamper the view to the towers in the current phase?", a: "No." },
      { q: "Depth of excavation", a: "18mtr." },
      { q: "Number of lifts in each wing", a: "Varies as per wing configuration, wing A and E have 3 lifts each other 4 wings have 2 lifts each." },
      { q: "Will the elevators be CCTV monitored", a: "TBD." },
      { q: "What is the speed of the elevator? (G to terrace time)", a: "1.25m/sec." },
      { q: "Is there a dedicated fireman lift?", a: "Not required as per MCGM/ FIRE SAFETY norms." },
      { q: "What happens to the elevator in case of a power failure? Are the elevators supported by a power back-up?", a: "Yes." },
      { q: "Can I take the elevator directly from my apartment to the parking?", a: "Yes." },
      { q: "Do you have any biometric access/card access to prevent unauthorized access to the elevators?", a: "No." },
      { q: "Whom should we connect if anyone is stuck in the lift or at midnight if the lift is non-functional?", a: "Lifts are equiped with emergency alarm." },
      { q: "Where exactly are these amenities located within the towers?", a: "at the ground floor, only spa is at top floor with pool." },
      { q: "Whether the amenities will be common in the complex, or will the towers have their individual amenities?", a: "sale and society will have separate amenities, but all sale amenities will be common for all 6 towers." },
      { q: "What are the different zones of amenities? And where are these zones located?", a: "Ground floor and terrace have amenities." },
      { q: "When are the amenities going to be operational?", a: "At the time of handover." },
      { q: "Is the project/individual towers compliant with the latest fire safety norms?", a: "yes." },
      { q: "Width of internal road for fire vehicle", a: "6 mtr wide." },
      { q: "What are the current security arrangements?", a: "5 Tier Security with boom barrier, RFID access, Video Door Phone, access control and gas detector." },
      { q: "Is Jodi provided by the developer? What are the Jodi options?", a: "Yes, Refer to stack sheet for jodi options." },
      { q: "What is the building height?", a: "Refer to stack sheet." },
      { q: "What is the carpet area of the flat/apartment/unit?", a: "Refer to stack sheet attached." },
      { q: "What are the types of flats/apartments/units available in the project?", a: "2, 3 and 4 BHK residences, Refer to flat mix shared for further details." }
    ]
  },
  "vansham": {
    projectName: "Chandak Vansham",
    developer: "Chandak",
    location: "Vile Parle (West), Mumbai",
    basicDetails: [
      "Land: 2.2 acres of development out of a 3.4 acre parcel",
      "Basements: 3 levels of parking",
      "All buildings connected from rooftop except 2 towers which are individually connected",
      "Total towers: 9 (T1, T2, T3, T4, T5, T6, T7, T8A, T8B)",
      "Floors: Ground + 14 upper floors (typical)",
      "Note: People from the previous society will occupy lower floors"
    ],
    floorBands: [
      "Floors 1–5: Reserved for redevelopment tenants",
      "Floors 6–9, 10–12, 13–14: Available for sale",
      "Floors 13–14: Generally not shown but shown if buyer offers good amount"
    ],
    amenities: {
      "Indoor": "Play Arena, Little Blossoms, Music Room, The Work Hub, Guest Haven, The Wellness Studio, The Blockbuster Room, The Celebration Hall, Gourmet Lounge, Spa, Fitness Junction, Café Connect",
      "Outdoor": "The Relaxation Nook, Joyful Swings, The Power Yard, Sports Court, The Aqua Retreat, The Golden Corner, The Happy Zone",
      "Terrace": "Skyline Pathway, Celestial Lounge, Windy Corners, The Sky Pavilion, The Grove, The Sunrise Deck, Visionary Studio, Solar Panel Area"
    },
    wings: {
      "Tower 1 (2 units/floor)": [
        "Unit 1: Signature 3 BHK — 1,365 sq ft (RERA carpet 1,237 sq ft) — floors 6–14",
        "Unit 2: Signature 3 BHK — 1,365 sq ft (RERA carpet 1,236 sq ft) — floors 6–14",
        "Unit 2 (2nd floor variant): Signature 3 BHK — 1,315 sq ft (RERA carpet 1,186 sq ft)"
      ],
      "Tower 2 (2 units/floor)": [
        "Unit 1: Regal 4 BHK — 1,885 sq ft (RERA carpet 1,650 sq ft) — floors 1–5, 7, 9–14"
      ],
      "Tower 3 (2 units/floor)": [
        "Unit 1: Signature 3 BHK — 1,370 sq ft (RERA carpet 1,200 sq ft) — floors 1–14",
        "Unit 2: Royal 2 BHK — 873 sq ft (RERA carpet 807 sq ft) — floors 9, 11–14"
      ],
      "Tower 4 (4 units/floor)": [
        "Unit 1: Signature 3 BHK — 1,311 sq ft (3rd floor), 1,335 sq ft (9th, 11th–14th floors)",
        "Unit 2: Signature 3 BHK — 1,335 sq ft (9th–14th floors)",
        "Unit 3: Royal 3 BHK — 1,085 sq ft (9th, 11th–14th floors)",
        "Unit 4: Royal 3 BHK — 1,007 sq ft (6th floor), 1,085 sq ft (9th, 11th–14th floors)"
      ],
      "Tower 5 (2 units/floor)": [
        "Unit 1: Signature 3 BHK — 1,370 sq ft (RERA carpet 1,200 sq ft) — floors 1–7, 9–14",
        "Unit 2: Royal 2 BHK — 841 sq ft (3rd floor), 873 sq ft (11th–14th floors)"
      ],
      "Tower 6 (2 units/floor)": [
        "Unit 1: Regal 4 BHK — 1,885 sq ft (RERA carpet 1,658 sq ft) — floors 1–7, 9–14",
        "Unit 1 (8th floor refuge): Signature 2 BHK — 1,252 sq ft (RERA carpet 1,072 sq ft)",
        "Unit 2: Royal 3 BHK — 1,158 sq ft (floors 1, 11–14)",
        "Unit 2 (8th floor refuge): Royal 2 BHK — 954 sq ft (RERA carpet 835 sq ft)"
      ],
      "Tower 7 (3 units/floor)": [
        "Unit 1: (Regal 4 BHK per typical plan)",
        "Unit 2: Royal 3 BHK — 1,158 sq ft (RERA carpet 1,039 sq ft) — floors 8, 11, 13–14",
        "Unit 3: Regal 4 BHK — 1,885 sq ft (RERA carpet 1,667 sq ft) — floors 1–14"
      ],
      "Tower 8A (3 units/floor)": [
        "Unit 1: Signature 3 BHK — 1,365 sq ft (RERA carpet 1,237 sq ft) — floors 9, 11–14",
        "Unit 2: Royal 3 BHK — 1,149 sq ft (RERA carpet 1,045 sq ft) — 5th floor",
        "Unit 3: Signature 3 BHK — 1,365 sq ft (RERA carpet 1,237 sq ft) — floors 8, 9, 12–14"
      ],
      "Tower 8B (3 units/floor)": [
        "Unit 1: Signature 3 BHK — 1,365 sq ft (RERA carpet 1,237 sq ft) — floors 10–14",
        "Unit 2: Signature 3 BHK — 1,315 sq ft (3rd floor), 1,365 sq ft (9th, 11th–14th floors)",
        "Unit 3: Royal 3 BHK — 1,149 sq ft (RERA carpet 1,045 sq ft) — floors 12, 14"
      ]
    },
    usp: [
      "Vile Parle location — prime land parcel",
      "Major parking space",
      "Rich amenity offering across ground and terrace levels"
    ],
    commonObjections: [
      "Why Vile Parle West over other western suburbs?",
      "Explain RERA carpet vs. total area to a confused buyer",
      "Handling the redevelopment tenant situation (lower floors occupied)",
      "Positioning the floor band strategy — why higher floors cost more",
      "Differentiating 2 BHK vs 3 BHK vs 4 BHK for different buyer profiles",
      "Selling the rooftop terrace and ground amenity package as a lifestyle USP",
      "Handling the 13th–14th floor pricing conversation",
      "Converting a premium buyer who is comparing Vile Parle vs Andheri"
    ],
    faqs: [
      { q: "When was Chandak Group founded? How many years of experience does Chandak Group have?", a: "1986 (38+ years of experience)" },
      { q: "How many projects in total have Chandak Group developed? What's the split of residential and commercial projects?", a: "30+ Completed projects" },
      { q: "How many ongoing projects does Chandak Group have in total as of date?", a: "9 ongoing projects" },
      { q: "Does the developer have a good reputation in the market?", a: "Yes" },
      { q: "How many sq.ft of area has Chandak Group delivered till date?", a: "12 Million+ sq.ft" },
      { q: "How many families (units sold) have Chandak Group catered to till date?", a: "11000+" },
      { q: "Total size of land parcel v/s Sale Plot (Phase B)", a: "Architect team" },
      { q: "Total Number of Flats V/s flats for sale", a: "Architect team" },
      { q: "Where is the project located?", a: "Kripa Nagar, Vile Parle (W)" },
      { q: "What is the nearest railway station?", a: "Vile Parle Railway Station" },
      { q: "Nearest bus station?", a: "Irla Bus Stop - 190 mtr" },
      { q: "What will be upcoming infrastructure in terms of road & metros?", a: "Metro Line 2B - Prem Nagar Metro Station" },
      { q: "How close is the existing Mumbai airport?", a: "3.3kms" },
      { q: "What are the access roads to the project site?", a: "Architect team" },
      { q: "What are nearby landmarks?", a: "Jain Derasar, Irla Market, CSMI Airport" },
      { q: "Which is the nearest market for daily supplies of vegetables, milk, etc.?", a: "Irla Market" },
      { q: "Which is the closest mall?", a: "Shoppers Stop, Dynamix Mall" },
      { q: "Which is the closest full-fledged hospital/medical room?", a: "KLS Memorial hospital, Cooper hospital" },
      { q: "Are there schools/colleges/universities/institutes nearby?", a: "NMIMS University, Ecole Mondiale World School" },
      { q: "Are there any petrol pumps nearby?", a: "HPCL Gas Station - 300 mtr, BPCL Gas Station - 400 mtr" },
      { q: "Are there decent restaurants / places to eat nearby?", a: "Will check" },
      { q: "Which are the closest places of worship nearby the project?", a: "Jain Derasar" },
      { q: "Which are the tourist places of interest nearby?", a: "Iskon Temple - 2.2kms, Juhu Beach - 2.4kms" },
      { q: "What are the tower names?", a: "No tower names" },
      { q: "What are the typology-wise names/nomenclature?", a: "Elite (2BHK-772, 3BHK-873); Royal (2BHK-873, 3BHK-1085/1150/1158/1252); Signature (2BHK-1062, 3BHK-1335/1365/1370); Regal (4BHK-1885)" },
      { q: "How green is the project?", a: "Architect team" },
      { q: "What will be the rental in future for each typology (2, 3 and 4 BHK apartments)? What's the market average?", a: "2BHK: 1L - 1.2L; 3BHK: 1.3L - 1.45L (Avg Y-o-Y Escalation: 5-7%)" },
      { q: "USPs of the project for marketing communication", a: "Ample car parking spaces, 1.2 acres of amenity and open space, Guest rooms, 3.4 acres of development" },
      { q: "All list of indoor amenities along with its sq.ft", a: "1. The Work Hub (520 SQ.FT, 20 persons), 2. Café Connect (600 SQ.FT, 20 persons), 3. Little Blossoms (300 SQ.FT, 10-12 kids), 4. Play Arena (990 SQ.FT, 18-20 persons), 5. Wellness Studio (630 SQ.FT, 10-12 persons), 6. Blockbuster Room (540 SQ.FT, 15 persons), 7. Guest Haven (800 SQ.FT, Family of 2), 8. Celebration Hall (1,300 SQ.FT, 70-80 persons), 9. Gourmet Lounge (250 SQ.FT, 8-10 persons), 10. Fitness Junction (870 SQ.FT, 15-20 persons), 11. Spa (900 SQ.FT, 8-10 persons)." },
      { q: "All list of outdoor ground amenities along with its sq.ft", a: "12. Wellness Loop (190m), 13. Relaxation Nook (1,000 SQ.FT), 14. Joyful Swings (400 SQ.FT, 10 persons), 15. Power Yard (2,000 SQ.FT, 8-10 persons), 16. Sports Court (4,000 SQ.FT, 2 courts), 17. Aqua Retreat (3,750 SQ.FT, 15-20 persons), 18. Golden Corner (500 SQ.FT, 5-8 persons), 19. Happy Zone (1,200 SQ.FT, 8-10 persons)." },
      { q: "What is the size of the Walking trail on the rooftop?", a: "Not provided (nan)" },
      { q: "What is the size of the Star Gazing Deck on the rooftop?", a: "1,000 SQ.FT." },
      { q: "What is the size of the Sit out spaces on the rooftop?", a: "2,350 SQ.FT." },
      { q: "What is the size of the Open Air Theater on the rooftop?", a: "1,800 SQ.FT." },
      { q: "What is the size of the Party lawn with barbecue on the rooftop?", a: "1,700 SQ.FT." },
      { q: "What is the size of the Yoga deck on the rooftop?", a: "1,200 SQ.FT." },
      { q: "What is the size of the Working spaces on the rooftop?", a: "1,400 SQ.FT." },
      { q: "Pedestrian entry and exit: Size, breadth, and location.", a: "Refer to plan. 1.5 m min wide pedestrian walkway." },
      { q: "Security cabins: Locations and details.", a: "One at entry and one at exit." },
      { q: "Number of gates: Size (height), location, and dimensions.", a: "2 gates - 4 m wide x 1.5 m high at entrance and exit." },
      { q: "What are the current security arrangements?", a: "5 Tier Security with boom barrier, RFID access, Video Door Phone, access control and gas detector." },
      { q: "Height of boundary wall: Overall and between sale and tenant buildings.", a: "1.5 m high compound wall, common for the entire premises." },
      { q: "Width of society boundaries.", a: "200 mm wide" },
      { q: "Distance between two towers.", a: "9 m between opposite towers." },
      { q: "Width of internal driveway and pedestrian pathway for sale buildings", a: "One way driveway and ramp is 4 m wide." },
      { q: "Width of internal driveway for redevelopment/tenant buildings", a: "Same as above." },
      { q: "Width of internal road for fire vehicle", a: "6 m wide." },
      { q: "Handicap Parking facilities?", a: "To be provided." },
      { q: "No of car parks in the complex", a: "As per MCGM norms." },
      { q: "No of visitor car parks", a: "As per MCGM norms." },
      { q: "No of 2-wheeler parking", a: "No" },
      { q: "Type of car park & size of a car park", a: "Sale parking: Surface; Visitor & society members: Mechanised parking system." },
      { q: "Is valet car parking available?", a: "No" },
      { q: "Access to car parking via ramp or car lift if any", a: "Ramp will be provided." },
      { q: "In case of a ramp for car parking, size of ramp and number of lanes", a: "One way driveway and ramp is 4 m wide. Entry and exit ramp is separate." },
      { q: "No of charging points for EV vehicles and their positioning", a: "As per IGBC norms." },
      { q: "Car washing area", a: "No" },
      { q: "Provision for wheelchair entry in the lobby.", a: "Accessible lobby at Ground level." },
      { q: "Rehab families access point", a: "Composite building. Access for society and sale is common." },
      { q: "Size, height, and dimensions of the entrance lobby.", a: "Height 2.95 m. Refer to amenity list for size." },
      { q: "Seating arrangement in the entrance lobby.", a: "As per layout." },
      { q: "Amenities in the lobby (e.g., AC, sofas).", a: "Sofas will be provided." },
      { q: "List of all amenities with their respective sizes and capacity.", a: "Refer to amenity list." },
      { q: "Certifications like IGBC.", a: "Will be taking for the project as a mandatory requirement." },
      { q: "Vermiculture facility availability.", a: "No" },
      { q: "Total area of amenities", a: "Refer separate list." },
      { q: "Any common amenities between Plot A & B", a: "Amenities will be shared across both plots." },
      { q: "Total amenities on rooftop with names and sizes", a: "Refer separate list." },
      { q: "Number of staircases and their width", a: "One staircase for each tower 1.5 m wide." },
      { q: "Whether we are providing solar panels", a: "Yes for power generation only." },
      { q: "Capacity of solar panels to generate electricity", a: "As per norms." },
      { q: "Placement of solar panels", a: "Terrace of Tower at specified locations." },
      { q: "Rainwater harvesting / STP", a: "Yes." },
      { q: "Warranty for solar panels", a: "To be checked with contract team." },
      { q: "Any waiting lounge for drivers", a: "Yes." },
      { q: "Any rainwater harvesting/STP (Sewage Treatment Plant) facility?", a: "Yes." },
      { q: "Capacity of STP for the whole project", a: "As per Approval." },
      { q: "How many staircases are provided to the building?", a: "One." },
      { q: "Where exactly are these amenities located within the towers?", a: "Ground floor." },
      { q: "What are the different zones of amenities? And where are these zones located?", a: "Ground floor." },
      { q: "Are there any gardens for senior citizens to walk or sit peacefully?", a: "Yes." },
      { q: "What about amenities for the children?", a: "Refer to amenity list." },
      { q: "Type of construction (Conventional, Casting, or Mivan).", a: "Combination of Aluminium and Conventional system." },
      { q: "Number of basements/podiums and their use.", a: "3 Basements for parking and services." },
      { q: "First habitable floor: Starting height.", a: "2.95 m." },
      { q: "Number of floors: Uniformity across towers.", a: "14 residential floors." },
      { q: "Type of foundation.", a: "Open foundation." },
      { q: "Shore piling or retaining wall details.", a: "As per Geotech consultant." },
      { q: "Floor plans and number of units per floor.", a: "Refer floor plan." },
      { q: "Exterior paint - water repellent and its warranty with brand", a: "Asian paint/Dulux/Berger or equivalent." },
      { q: "Whether the top slab will have double casting as the terrace will have amenities", a: "No." },
      { q: "Type of internal wall plaster (Cement/POP/Neru/Gypsum)", a: "Gypsum." },
      { q: "Size of chajja", a: "300 to 450 mm." },
      { q: "Depth of chajja from the slab", a: "600 mm below floor level." },
      { q: "Floor-to-ceiling height and slab-to-slab height", a: "Floor to ceiling: 2.8 m; Slab-to-slab: 2.95 m (unfinished)." },
      { q: "Type of paint for flats' internal walls and brand", a: "Asian paint/Dulux/Berger or equivalent." },
      { q: "What are the options of view from different flats and heights?", a: "North: Future development & 13.2 m road; East/South: Airport view; West: Derasar view." },
      { q: "What is the depth of excavation and RCC foundation?", a: "12 m below ground level." },
      { q: "Would the towers planned for the next set of launches hamper the view to the towers in the current phase?", a: "Refer point no 130." },
      { q: "Which quality/grade of cement is used for construction?", a: "Check with contract team." },
      { q: "Grade of cement used for walls and slabs", a: "Check with contract team." },
      { q: "When are the amenities going to be operational?", a: "At the time of handover." },
      { q: "What kind of waterproofing treatment is carried out for the exterior of the building, and its service tenure?", a: "As per contract team." },
      { q: "What is the building height?", a: "45.95m." },
      { q: "Whether supply of water from underground tank or OHWT", a: "Underground." },
      { q: "Brand, dimensions, passenger capacity, and service period of elevators.", a: "OTIS/SCHINDLER or equivalent." },
      { q: "Whether elevators go to the terrace/basement.", a: "Basement levels only; not to terrace. Fire elevator Ground to last residential." },
      { q: "Accessibility for senior citizens to the terrace if elevators don't go.", a: "Staircase only." },
      { q: "Dedicated/express elevators for terrace amenities.", a: "No." },
      { q: "Service period of elevators", a: "Check with contracts team." },
      { q: "Service lift for carrying furniture and materials", a: "Yes, one dedicated lift per tower." },
      { q: "What is the speed of the elevator?", a: "1.25m/sec." },
      { q: "Is there a dedicated fireman lift?", a: "Not required as per MCGM/FIRE SAFETY norms." },
      { q: "What happens to the elevator in case of a power failure? supported by power back-up?", a: "Yes." },
      { q: "Can I take the elevator directly from my apartment to the parking?", a: "Yes." },
      { q: "Total size of the land parcel.", a: "7952.32 sq.mt." },
      { q: "Land parcel area split (sale, tenant, RG).", a: "Composite development. RG as per norms." },
      { q: "Dimensions and frontage of the land.", a: "290 feet." },
      { q: "Total number of flats for sale and their saleable area.", a: "Refer stack sheet." },
      { q: "Planned expansions around the project.", a: "Plot A Future development." },
      { q: "Density of the project", a: "To be provided." },
      { q: "No of refuge flats and size of a refuge area", a: "As per MCGM norms." },
      { q: "At what height from the sea level (altitude) is the project located?", a: "5.25 m." },
      { q: "What is the area planned for phase-1 launch?", a: "Refer stack sheet." },
      { q: "Currently up to what stage is the project developed?", a: "Site work ongoing." },
      { q: "Total number of units?", a: "Refer stack sheet." },
      { q: "Distance between the flats (Adjacent and opposite units)", a: "To be provided." },
      { q: "Number of towers", a: "9" },
      { q: "Garbage chute availability.", a: "No. Organic waste composter as per norms." },
      { q: "Provision for power backup", a: "Alternate power for common areas and fire lifts." },
      { q: "Position of generators", a: "No." },
      { q: "No of servants' toilets and locations", a: "Driver toilet at Basement and ground." },
      { q: "Borewell", a: "No" },
      { q: "Provision for AC in the flat", a: "Only Sleeve provision." },
      { q: "Provision for keeping the outdoor units of AC", a: "As per design intent." },
      { q: "Provision for drain pipe of AC", a: "Yes." },
      { q: "Two-phase or three-phase wiring", a: "As per Design requirements." },
      { q: "Provision for landline/internet/cable", a: "Provision." },
      { q: "Provision for LV for fiber optics", a: "Yes." },
      { q: "Provision for drying clothes", a: "Utility and passage areas." },
      { q: "Capacity of domestic water tank and location", a: "Basement 1, as per norms." },
      { q: "Capacity of fire water tank", a: "As per norms." },
      { q: "Is there storm water management in the project? Any suction pumps?", a: "Yes." },
      { q: "Provision for sunlight and ventilation on the floors", a: "Maximum size windows." },
      { q: "How green is the project?", a: "IGBC Certified." },
      { q: "What is the internal flooring we are offering in the flat", a: "Marble (living/passage/dining), Tiles (Kitchen/Bedroom), Anti-skid (Deck/Utility)." },
      { q: "Size and make of tiles for flooring", a: "Kajaria/Jhonson/Simpollo/Somany or equivalent." },
      { q: "Size and make of tiles for bathroom/kitchen wall", a: "TBD." },
      { q: "Height of dado tiles in the kitchen and washrooms", a: "Window top." },
      { q: "Size of windows", a: "As per guidelines." },
      { q: "Provision for mosquito nets", a: "No." },
      { q: "No of window tracks", a: "2 or 3 tracks." },
      { q: "Type of glass used in windows", a: "Clear Glass." },
      { q: "The doors provided will be FRP or wooden", a: "Laminated flush doors." },
      { q: "Door frames - wooden or marble", a: "Wooden (main/bedroom), Granite (Toilet)." },
      { q: "Kitchen platform length and breadth", a: "Length varies, Width 2'0\"." },
      { q: "Material of kitchen platform", a: "Refer floor plan." },
      { q: "Size of kitchen sink", a: "SS SINK 16\"X22\"." },
      { q: "Whether washrooms will have concealed or open flush tanks", a: "Concealed." },
      { q: "Whether the shower area will have a glass partition", a: "No." },
      { q: "Window frame - granite or marble", a: "Granite." },
      { q: "Are we giving loft in washroom?", a: "No." },
      { q: "Will there be marble or tiles in the lobby?", a: "Tiles." },
      { q: "Whether we are providing safety railing and material", a: "Balconies & Utility area." },
      { q: "Height of safety railing", a: "As per standard norms." },
      { q: "Whether the shower area will have a water trap", a: "Yes, one per toilet." },
      { q: "Water sprinklers in flats", a: "Open sprinklers." },
      { q: "Whether False ceiling provided ?", a: "No." },
      { q: "Brand of sanitary and faucets", a: "Jaquar/Cera/Hindware or equivalent." },
      { q: "Warranty of faucets", a: "As per brand policy." },
      { q: "Whether the top floors will have a separate water line", a: "MEP design ensures pressure." },
      { q: "Provision for washing machine and fridge", a: "Electrical provision provided." },
      { q: "Are we providing geyser in bathrooms?", a: "Yes, Reputed Brand." },
      { q: "Door lock brand", a: "Godrej/Dorset/Yale or equivalent." },
      { q: "Architect & Construction Partners", a: "Architect: Kapadia Associates; Structure: Pravin Gala consultants." },
      { q: "Are we providing a lightning arrester?", a: "As per norms." },
      { q: "Is the building earthquake-resistant?", a: "Yes (Around 6 to 7 on Richter Scale)." },
      { q: "Seismic zone of our project", a: "Zone 3" },
      { q: "Fire chute", a: "No" },
      { q: "Will the elevators be CCTV monitored", a: "To be discussed" },
      { q: "Biometric access/card access?", a: "No" },
      { q: "Whom should we connect if anyone is stuck in the lift?", a: "Emergency alarm in lifts." },
      { q: "Is the project/individual towers compliant with the latest fire safety norms?", a: "Yes" },
      { q: "Are all the apartments vastu compliant?", a: "Limited to entry and kitchen only" },
      { q: "Vastu consultant name", a: "To be provided." },
      { q: "What is the overall project USP?", a: "Gated community, ground floor landscape, deck provision, well ventilated." },
      { q: "What is the design and feature description of the terrace?", a: "Refer separate sheet." },
    ]
  },
  "Highscape City": {
    projectName: "Chandak Highscape City",
    developer: "Chandak Group",
    location: "Chembur (East), Mumbai — Off Eastern Freeway, Sahyadri Nagar, Chembur (E), Mumbai – 400074",
    basicDetails: [
      "Land: ~13 acres residential development with 8 tower and only 4 towers being built currently",
      "Basement + Ground + 1st floor: Retail / commercial use",
      "Parking: ~5–6 levels",
      "Amenities: Concentrated on 6th floor podium + terrace levels",
      "Clubhouse: ~20,500 sq ft, 3 floors",
      "Total amenity area: ~52,000 sq ft",
      "SRA component: Present (separate building)",
      "Total towers: 3 — Summit, Pinnacle, Skyline"
    ],
    floorBands: [
      "2-15",
      "16-24",
      "25-31",
      "32-35"
    ],
    amenities: {
      "Indoor": "Large clubhouse (~20,500 sq ft), Fitness centre, Indoor recreation spaces, Community halls",
      "Outdoor": "Open landscaped spaces across township, Recreation zones between towers",
      "Podium / Terrace": "Major lifestyle amenities on 6th floor podium, Landscaped lifestyle decks, Terrace-level zones"
    },
    wings: {
      "Tower: Summit (Standard Floor Mix)": [
        "Units 1 & 2: Elite 2 BHK — RERA carpet 660 sq ft / Total 660 sq ft (no additional area)",
        "Units 3, 4 & 5: 1 BHK — RERA carpet 407 sq ft / Total 407 sq ft (no additional area)",
        "Units 6, 7, 8, 9, 10 & 11: 1 BHK — RERA carpet 428 sq ft / Total 428 sq ft (no additional area)"
      ],
      "Tower: Summit (Jodi Options)": [
        "Units 1 & 2 → 2+2 Jodi: RERA carpet 1,330 sq ft / Total 1,330 sq ft (no additional area)",
        "Units 3 & 4 → 1+1 Jodi: RERA carpet 820 sq ft / Total 820 sq ft",
        "Units 6 & 7 → 1+1 Jodi: RERA carpet 842 sq ft / Total 842 sq ft",
        "Units 8 & 9 → 1+1 Jodi: RERA carpet 842 sq ft / Total 842 sq ft",
        "Units 10 & 11 → 1+1 Jodi: RERA carpet 863 sq ft / Total 863 sq ft"
      ],
      "Tower: Pinnacle (Standard Floors below 32nd)": [
        "Units 1, 4, 5 & 8: 1 BHK — RERA carpet 407 sq ft / Total 407 sq ft (no additional area)",
        "Units 2, 3, 6 & 7: Elite 2 BHK — RERA carpet 602 sq ft + Additional 36 sq ft / Total 638 sq ft"
      ],
      "Tower: Pinnacle (32nd Floor & Above)": [
        "Units 1, 4, 5 & 8: 1 BHK — RERA carpet 414 sq ft + Additional 28 sq ft / Total 442 sq ft",
        "Units 2, 3, 6 & 7: Elite 2 BHK — RERA carpet 605 sq ft + Additional 62 sq ft / Total 667 sq ft"
      ],
      "Tower: Pinnacle (Jodi Options below 32nd)": [
        "Units 1 & 2 → 1+2 Jodi: RERA carpet 1,015 sq ft + Additional 36 sq ft / Total 1,051 sq ft",
        "Units 3 & 4 → 2+1 Jodi: RERA carpet 1,015 sq ft + Additional 36 sq ft / Total 1,051 sq ft",
        "Units 5 & 6 → 1+2 Jodi: RERA carpet 1,015 sq ft + Additional 36 sq ft / Total 1,051 sq ft",
        "Units 7 & 8 → 2+1 Jodi: RERA carpet 1,015 sq ft + Additional 36 sq ft / Total 1,051 sq ft"
      ],
      "Tower: Pinnacle (Jodi Options 32nd & above)": [
        "Units 1 & 2 → 2+1 Jodi: RERA carpet 1,025 sq ft + Additional 92 sq ft / Total 1,117 sq ft",
        "Units 3 & 4 → 2+1 Jodi: RERA carpet 1,025 sq ft + Additional 92 sq ft / Total 1,117 sq ft",
        "Units 5 & 6 → 2+1 Jodi: RERA carpet 1,025 sq ft + Additional 92 sq ft / Total 1,117 sq ft",
        "Units 7 & 8 → 2+1 Jodi: RERA carpet 1,025 sq ft + Additional 92 sq ft / Total 1,117 sq ft"
      ],
      "Tower: Skyline (Standard Floors below 32nd)": [
        "Units 1 & 2: Elite 3 BHK — RERA carpet 812 sq ft + Additional 36 sq ft / Total 848 sq ft",
        "Units 3, 6, 7 & 10: 1 BHK — RERA carpet 405 sq ft / Total 405 sq ft (no additional area)",
        "Units 4 & 5: Elite 2 BHK — RERA carpet 625 sq ft + Additional 36 sq ft / Total 661 sq ft",
        "Units 8 & 9: Elite 3 BHK — RERA carpet 809 sq ft + Additional 39 sq ft / Total 848 sq ft"
      ],
      "Tower: Skyline (32nd Floor & Above)": [
        "Units 1 & 2: Signature 3 BHK — RERA carpet 819 sq ft + Additional 65 sq ft / Total 884 sq ft",
        "Units 3, 6, 7 & 10: 1 BHK — RERA carpet 412 sq ft + Additional 28 sq ft / Total 440 sq ft",
        "Units 4 & 5: Royale 2 BHK — RERA carpet 627 sq ft + Additional 61 sq ft / Total 688 sq ft",
        "Units 8 & 9: Royale 3 BHK — RERA carpet 811 sq ft + Additional 65 sq ft / Total 876 sq ft",
        "Unit 9 (alternative variant): Royale 2 BHK — RERA carpet 670 sq ft + Additional 38 sq ft / Total 708 sq ft"
      ],
      "Tower: Skyline (Jodi Options below 32nd)": [
        "Units 1 & 2 → 3+3 Jodi: RERA carpet 1,633 sq ft + Additional 74 sq ft / Total 1,707 sq ft",
        "Units 3 & 4 → 1+2 Jodi: RERA carpet 1,037 sq ft + Additional 35 sq ft / Total 1,072 sq ft",
        "Units 5 & 6 → 2+1 Jodi: RERA carpet 1,037 sq ft + Additional 35 sq ft / Total 1,072 sq ft",
        "Units 7 & 8 → 1+3 Jodi: RERA carpet 1,222 sq ft + Additional 38 sq ft / Total 1,260 sq ft",
        "Units 9 & 10 → 3+1 Jodi: RERA carpet 1,222 sq ft + Additional 38 sq ft / Total 1,260 sq ft"
      ],
      "Tower: Skyline (Jodi Options 32nd & above)": [
        "Units 1 & 2 → 3+3 Jodi: RERA carpet 1,648 sq ft + Additional 132 sq ft / Total 1,780 sq ft",
        "Units 3 & 4 → 2+1 Jodi: RERA carpet 1,048 sq ft + Additional 92 sq ft / Total 1,140 sq ft",
        "Units 5 & 6 → 2+1 Jodi: RERA carpet 1,048 sq ft + Additional 92 sq ft / Total 1,140 sq ft",
        "Units 7 & 8 → 3+1 Jodi: RERA carpet 1,232 sq ft + Additional 96 sq ft / Total 1,328 sq ft",
        "Units 9 & 10 → 3+1 Jodi: RERA carpet 1,232 sq ft + Additional 96 sq ft / Total 1,328 sq ft"
      ]
    },
    usp: [
      "One of the largest land parcels in Chembur — township-scale development",
      "~52,000 sq ft of total amenities including a ~20,500 sq ft clubhouse",
      "Strong connectivity via Eastern Freeway and DP Road",
      "Future ecosystem: schools and hospitals planned within the township",
      "Mixed inventory — appeals to investors, first-time buyers, nuclear families, and premium upgrade buyers",
      "Phase-based tower delivery with multiple towers under construction simultaneously"
    ],
    commonObjections: [
      "Why Chembur East over other central suburbs (Ghatkopar, Wadala, Kurla)",
      "Explaining the township-scale advantage to a buyer",
      "Handling the SRA presence concern from a buyer",
      "Differentiating Summit vs Pinnacle vs Skyline for different buyer profiles",
      "Explaining Jodi configurations and their value proposition",
      "Selling the amenity-heavy lifestyle (~52,000 sq ft amenities, ~20,500 sq ft clubhouse)",
      "Justifying higher floor premium pricing (32nd floor and above)",
      "Investor vs end-user positioning conversation",
      "Compact unit vs larger luxury unit decision for the right buyer",
      "Phase-based delivery and possession timeline handling",
      "Explaining RERA carpet vs total area (additional area component) to a confused buyer",
      "Comparing Chembur vs Ghatkopar / Wadala / Kurla for location objection handling"
    ],
    faqs: [
      { q: "What is the lobby size for all 4 lobbies and the distance between them?", a: "To Be Provided From Design Team" },
      { q: "Where are the lobbies located across all 4 towers?", a: "At Podium 1 Internal Facing" },
      { q: "What are the refuge areas and floors for all towers?", a: "As Per Stack" },
      { q: "Where is the SUV car parking located for cars above 2.0 tons?", a: "To Be Provided From Design Team" },
      { q: "What is the residential parking level-wise count?", a: "To Be Provided From Design Team" },
      { q: "Where is the car washing area located?", a: "Provisions For The Same Will Be Made" },
      { q: "What is the EV facility — location and size plan?", a: "10% Of Total Car Parks As Per Government Norms" },
      { q: "How many parking slots does a 3 BHK get?", a: "1 Car Park" },
      { q: "Is the road from the entry gate accessible after the parking area?", a: "Same Entry And Exit Points" },
      { q: "What is the retail parking location and count?", a: "G Floor Entry Exit Separate From Residential" },
      { q: "What is the paint brand used in residential units?", a: "Asian Paint / Equivalent Brands" },
      { q: "What is the tiles brand for the kitchen and living room?", a: "Kajaria / Simpolo / Equivalent Brands" },
      { q: "What is the tiles brand for bathrooms?", a: "Kajaria / Simpolo / Equivalent Brands" },
      { q: "What is the quality, brand, and soundproofing of the windows in the sample flat?", a: "Anodized Aluminium Sliding Windows" },
      { q: "What is the arrangement for the service lift for furniture and material per tower?", a: "Any One Of The Existing Lifts To Be Converted Into Service Lift" },
      { q: "What is the lift brand?", a: "Otis / Schindler / Equivalent Brands" },
      { q: "Does the project have a stretcher lift?", a: "Not Available" },
      { q: "Is there a provision for a servant toilet?", a: "Provisions On The Podium Level" },
      { q: "What is the entry/exit arrangement for Phase 1B?", a: "Remains The Same As Phase 1A" },
      { q: "What is the walkway/pathway connection from Skyline to Pinnacle?", a: "Ground Level To E-Deck Level Connected" },
      { q: "What is the distance of the DP Road from Shivaji Circle and its completion timeline?", a: "As Per Government Norms" },
      { q: "What is the distance of the DP Road from the Freeway and its completion timeline?", a: "As Per Government Norms" },
      { q: "Who is the consultant for amenities planning?", a: "NNA Architects" },
      { q: "What is the depth of the swimming pool?", a: "5 Ft (Adult Pool) And 2 Ft (Kids Pool)" },
      { q: "What is the capacity of the amphitheater?", a: "Approx 100–150 People" },
      { q: "What is the total length of the jogging/cycling track?", a: "250 Meters" },
      { q: "What is the size of the kids play area?", a: "6500 Sq Ft — Outdoor & Indoor Dedicated For Kids Play Area" },
      { q: "Are there amenities on the terrace?", a: "Yes" },
      { q: "What is the size of the Sky Deck area?", a: "To Be Launched In Phase 1B" },
      { q: "What is the size and capacity of the banquet hall?", a: "3500 Sq Ft — Capacity Of 250 People" },
      { q: "What is the size of the gym area?", a: "3400 Sq Ft" },
      { q: "Where is the STP (Sewage Treatment Plant) located?", a: "Yes, In Basement T8" },
      { q: "Where is the rainwater harvesting located?", a: "Yes, In Basement T7" },
      { q: "Where are the solar panels located?", a: "Yes, As Per Norms" },
      { q: "Where is the storm water management system located?", a: "Yes, As Per Norms" },
      { q: "When will the amenities be ready — Builder Possession or RERA Possession?", a: "As Per RERA" }
    ]
  },
  "treesourus": {
    projectName: "Chandak Treesourus",
    developer: "Chandak Group",
    location: "Malad (West), Mumbai — Corner of Nana Bhai Bhuleshwar Marg and Chincholi Bunder Road",
    basicDetails: [
      "Tagline: Where Nature Comes Home",
      "Land: 4 acres being developed out of a total 14 acre parcel (1 acre goes to BMC, 3 acres remaining/future development)",
      "Previously owned by Bombay Talkies, now owned by Chandak",
      "Basements: 3 levels of basement parking",
      "Parking: LOL parking system + 3 basement levels",
      "Total towers: 2 — Tower 1 and Tower 2",
      "Floors: Habitable floors from 2nd to 45th",
      "Podium levels: 2nd to 6th and 8th floors (parking + lobby)",
      "Refuge floors: 7th, 14th, 21st, 28th, 35th floors",
      "Amenity floor: 11th floor (indoor + outdoor amenities)",
      "Terrace: Rooftop amenities",
      "MahaRERA Registration No.: P51800048658",
      "Project financed by: ICICI Bank Limited"
    ],
    floorBands: [
      "Floors 2–20: Band 1 — entry pricing tier",
      "Floors 21–29: Band 2 — mid pricing tier",
      "Floors 30–35: Band 3 — upper mid tier",
      "Floors 36–45: Band 4 — premium pricing tier",
      "Floor pricing increment logic: Each floor within Band 1, Band 2, and Band 3 carries an increment of Rs. 1,000 per floor over the floor below. The jump between Band 3 (floor 35) and Band 4 (floor 36 onwards) is Rs. 3,000 per floor. Within Band 4, each floor continues at Rs. 1,000 increment per floor above the Band 4 base"
    ],
    amenities: {
      "11th Floor (Amenity Floor)": "Banquet Hall, Mini Squash Court, Indoor Games room, Virtual Games Simulator, Gym, LMR (Leisure and Meeting Room), Ladies Restroom, Gents Restroom, Lounge, Mini Theatre, Spa/Wellness, Guest Room 1, Guest Room 2, Canopy Dining, Private Dining, Kitchen, Pool Deck, Infinity Pool, Sun Deck, Kids Play Area, Barbeque zone, Viewing Deck",
      "Terrace Floor": "Floor Games, Kids Play Area, Graphic Wall, Hobby / Creative Corner, Reflexology Area, Senior Citizen Area, LMR, Crossfit Area, Rowing Area, Open Gym, Boxing Area, Work From Terrace, Reading Deck, Skating Deck, Sunset Deck, Sunset Lawn, Barbecue Deck, Seating Deck, Pool Lawn, Meditation Deck, Hammock Deck"
    },
    wings: {
      "Tower 2 — Typical Floor (2nd to 6th & 8th floor podium levels)": [
        "Flat 1: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft — 2 BHK",
        "Flat 2: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft — 2 BHK",
        "Flat 3: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft — 2 BHK",
        "Flat 4: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft — 2 BHK",
        "Flat 5: RERA carpet 672 sq ft + Additional 50 sq ft / Total 722 sq ft — 2 BHK",
        "Flat 6: RERA carpet 668 sq ft + Additional 50 sq ft / Total 718 sq ft — 2 BHK"
      ],
      "Tower 2 — Refuge Floor (7th floor)": [
        "Flat 1: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft",
        "Flat 2: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft",
        "Flat 3: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft",
        "Flat 4: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft"
      ],
      "Tower 2 — Typical Plan (habitable floors, standard)": [
        "Flat 1: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft — 2 BHK",
        "Flat 2: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft — 2 BHK",
        "Flat 3: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft — 2 BHK",
        "Flat 4: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft — 2 BHK",
        "Flat 5: RERA carpet 672 sq ft + Additional 50 sq ft / Total 722 sq ft — 2 BHK",
        "Flat 6: RERA carpet 668 sq ft + Additional 50 sq ft / Total 718 sq ft — 2 BHK",
        "Flat 7: RERA carpet 955 sq ft + Additional 64 sq ft / Total 1,019 sq ft — 3 BHK",
        "Flat 8: RERA carpet 676 sq ft + Additional 55 sq ft / Total 731 sq ft — 2 BHK"
      ],
      "Tower 2 — Refuge Plan (14th, 21st, 28th, 35th floors)": [
        "Flat 1: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft",
        "Flat 2: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft",
        "Flat 3: RERA carpet 682 sq ft + Additional 56 sq ft / Total 738 sq ft",
        "Flat 4: RERA carpet 689 sq ft + Additional 55 sq ft / Total 744 sq ft",
        "Flat 7: RERA carpet 955 sq ft + Additional 64 sq ft / Total 1,019 sq ft",
        "Flat 8: RERA carpet 676 sq ft + Additional 55 sq ft / Total 731 sq ft"
      ],
      "Individual Unit Type Details — Tower 2": [
        "2 BHK — 718 sq ft (Flat 6): Rooms: Bedroom 01 (10'0\"×12'7\"), Bedroom 02 (11'0\"×9'3\"), Living & Dining (10'6\"×20'0\"), Kitchen (10'0\"×7'0\"), Utility (3'3\"×5'2\"), Bath 01 (4'0\"×7'7\"), Bath 02 (7'6\"×4'0\"), Deck (5'10\"×5'9\")",
        "2 BHK — 722 sq ft (Flat 5): Rooms: Bedroom 01 (10'0\"×12'9\"), Bedroom 02 (11'0\"×9'5\"), Living & Dining (10'6\"×15'2\"), Kitchen (10'0\"×7'0\"), Utility (3'3\"×5'2\"), Bath 01 (4'0\"×7'7\"), Bath 02 (7'6\"×4'0\"), Deck (5'10\"×5'9\")",
        "2 BHK — 731 sq ft (Flat 8): Rooms: Bedroom 01 (10'0\"×12'9\"), Bedroom 02 (11'0\"×9'3\"), Living & Dining (10'6\"×20'5\"), Kitchen (10'0\"×7'0\"), Utility (3'3\"×5'2\"), Bath 01 (4'0\"×7'9\"), Bath 02 (7'4\"×4'0\"), Deck (6'9\"×5'9\")",
        "2 BHK — 738 sq ft (Flats 2 & 3): Rooms: Bedroom 01 (10'0\"×12'4\"), Bedroom 02 (11'0\"×8'2\"), Living & Dining (10'6\"×20'3\"), Kitchen (10'0\"×7'0\"), Utility (3'4\"×5'2\"), Bath 01 (4'0\"×7'8\"), Bath 02 (7'6\"×4'0\"), Deck (6'9\"×5'9\")",
        "2 BHK — 744 sq ft (Flats 1 & 4): Rooms: Bedroom 01 (10'0\"×12'10\"), Bedroom 02 (11'0\"×8'6\"), Living & Dining (10'6\"×20'3\"), Kitchen (10'0\"×7'0\"), Utility (4'11\"×3'4\"), Bath 01 (4'0\"×7'8\"), Bath 02 (7'4\"×4'0\"), Deck (6'9\"×5'9\")",
        "3 BHK — 1,019 sq ft (Flat 7): Rooms: Bedroom 01 (10'0\"×13'0\"), Bedroom 02 (10'0\"×13'0\"), Bedroom 03 (13'2\"×11'0\"), Living & Dining (10'6\"×20'3\"), Kitchen (8'0\"×10'11\"), Utility (5'3\"×4'9\"), Bath 01 (4'0\"×7'6\"), Bath 02 (4'0\"×7'6\"), Bath 03 (7'6\"×4'0\"), Deck (6'9\"×5'9\")"
      ],
      "Jodi Options — Tower 2": [
        "Jodi — 1,451 sq ft (2+2 Jodi): RERA carpet 1,346 sq ft + Additional 103 sq ft / Total 1,451 sq ft, Layout: 4 bedrooms, study room, balcony, large living & dining (21'7\"×20'0\"), combined kitchen (15'0\"×7'0\"), deck (12'2\"×5'9\")",
        "Jodi — 1,495 sq ft (variant A — 2+2 Jodi, standard layout): RERA carpet 1,381 sq ft + Additional 114 sq ft / Total 1,495 sq ft, Layout: 4 bedrooms, study room, balcony, large living & dining (21'7\"×20'3\"), kitchen (10'0\"×7'0\"), deck (14'0\"×5'9\")",
        "Jodi — 1,495 sq ft (variant B — Master suite Jodi): RERA carpet 1,381 sq ft + Additional 114 sq ft / Total 1,495 sq ft, Layout: Master bedroom with walk-in wardrobe, dresser, his & her bath, 2 additional bedrooms, servants room, store, entrance foyer, deck (14'2\"×5'9\")",
        "Jodi — 1,761 sq ft (3+2 Jodi): RERA carpet 1,639 sq ft + Additional 122 sq ft / Total 1,761 sq ft, Layout: 5 bedrooms, study room, balcony, large living & dining (21'7\"×20'3\"), kitchen (17'0\"×7'0\"), deck (14'0\"×5'9\")"
      ],
      "Note on Tower 1": [
        "Tower 1 is a separate tower within the same project. Tower 1 floor plans follow their own unit layout and numbering. Use the same RERA carpet / additional area / total area framework for any Tower 1 questions. Tower 1 and Tower 2 share the same amenity floor (11th) and terrace, as both towers are part of the same connected development."
      ]
    },
    usp: [
      "Prime Malad West location — SV Road and Link Road both accessible, 2 metro stations close by, 2 railway stations nearby",
      "Multiple hospitals close by",
      "Goregaon–Mulund Link Road and Coastal Road under development — will significantly increase connectivity",
      "Large 14-acre land parcel in Malad West — rare for the location",
      "NOT a redevelopment project — fresh greenfield development",
      "Nature-themed positioning with lush green landscaping across the entire parcel",
      "Rich amenity offering on 11th floor and rooftop terrace"
    ],
    commonObjections: [
      "Why Malad West over other western suburbs",
      "Explaining the 14-acre land parcel advantage and the nature-themed positioning",
      "Handling the \"only 2 BHK\" perception — the 3 BHK option exists in Tower 2 (Flat 7), and Jodi configurations offer larger homes",
      "Explaining the Jodi concept and its value for joint families or premium buyers — four Jodi variants available ranging from 1,451 to 1,761 sq ft",
      "Selling the SV Road + Link Road + metro + railway connectivity as a multi-modal USP",
      "Explaining the Goregaon–Mulund Link Road and Coastal Road development as future connectivity upside",
      "Explaining the floor band pricing strategy — Rs. 1,000 increment per floor within bands, Rs. 3,000 jump at the Band 3 to Band 4 transition (floor 35 to 36)",
      "Selling the 11th floor amenity deck and rooftop terrace as lifestyle differentiators",
      "Converting a buyer comparing Malad West vs Goregaon or Andheri",
      "Explaining RERA carpet vs total area including the additional area (deck) component",
      "Addressing the \"not a redevelopment\" positioning vs nearby redevelopment projects",
      "Differentiating Tower 1 vs Tower 2 for a buyer who asks about the difference",
      "Handling possession timeline questions across both towers"
    ],
    faqs: [
      { q: "Total Size of Land Parcel", a: "16075.90 sq m" },
      { q: "Sale component land parcel", a: "4822 sq m" },
      { q: "Size of land parcel used for Construction of Building", a: "4822 sq m" },
      { q: "Total no of flats for sale", a: "630 no of flats" },
      { q: "Total squarefeet for sale", a: "508353 sq ft" },
      { q: "RG Land Parcel (What will be made)", a: "Handed over to MCGM" },
      { q: "Existing litigations & impact on project", a: "Legal Team" },
      { q: "Conveyance status", a: "Legal Team" },
      { q: "Dimensions of the land and what is the frontage", a: "appx 134m x 154m, frontage along nanabhai bhuleshwar road appx 31m" },
      { q: "Size, number and positioning of gates for entry and exit", a: "9m wide entry and exit gate from Nanabhai bhuleshwar marg" },
      { q: "Pedestrian entry and exit", a: "This will be from the Nanabhai Bhuleshwar Marg" },
      { q: "Depth of Excavation", a: "appx 18m" },
      { q: "Type of foundation", a: "Raft Foundation" },
      { q: "Shore piling or retention wall", a: "Yes" },
      { q: "Type of construction (Conventional or Casting)", a: "RCC Frame structure" },
      { q: "Size, height & Dimension of Entrance lobby", a: "appx 20m x 8m, 6m height" },
      { q: "Seating arrangement of entrance lobby", a: "Shown in plan" },
      { q: "AC, Sofas and the amenities in the lobby", a: "Airconditioned lobby" },
      { q: "Provision for wheelchair entry in the lobby", a: "Accessible" },
      { q: "Security cabins and its location", a: "at the entry gate" },
      { q: "Width of internal road for Fire vehicle", a: "9m wide driveway" },
      { q: "Contractor name and his background", a: "Projects team to provide" },
      { q: "Consultant for amenities and his background", a: "Practice(Architect) & GSA(Landscape Architect) J+W(Structure Consultant)" },
      { q: "No of car parks in the complex", a: "802" },
      { q: "No of visitor car park", a: "As per regulations" },
      { q: "Type of car park", a: "Puzzle, Stack, and Surface" },
      { q: "Size of car park & weight capacity of each puzzle", a: "2.5 x 5.5m and 2.3 x 4.5m puzzle capacity 2.5 ton" },
      { q: "Waiting time for car park in case of puzzle", a: "appx 2-3 mins" },
      { q: "Height of boundary wall", a: "appx 5'" },
      { q: "Access to car parking via ramp or car lift", a: "Ramp" },
      { q: "No of basements/podiums?", a: "3 nos of Basements, 9nos of podiums" },
      { q: "Total area of amenities", a: "11th floor indoor amenities area appx 14500 sqft" },
      { q: "Number of amenities", a: "Gym, Guest Rooms, Café zone, Private Dining, Mini Theatre, Lounge, Banquet hall, Spa zone, Indoor Games, Kids play area, Wellness zone, Mini Squash, Library, Infinity pool with deck, Multipurpose lawn, Kids play area, Senior citizen Area" },
      { q: "Whether the amenities will be common in the complex or the towers will have their individual amenities", a: "All amenities will be common for both towers" },
      { q: "Human capacity of the amenities like, clubhouse, community hall etc", a: "Banquet Hall - 40 Persons, Auditorium - 12 person" },
      { q: "Depth of swimming pool and kids pool and its Dimensions", a: "Swimming pool 15.9x8m depth 1.2m/4', Kids pool 3.3mx1.6m depth 0.9mor 3'" },
      { q: "Total amenities on rooftop", a: "Party Lawn, Yoga Lawn, sky lounge, Youth Corner, Kids Play Area, Hobby creative corner, Senior Citizen Area, Crossfit area and open gym, Work from Garden/Terrace" },
      { q: "The height of terrace wall", a: "1.5m" },
      { q: "Whether the top slab will have double casting as terrace will have amenities", a: "no" },
      { q: "Waterproofing provisions in the building and service tenure", a: "Projects team to provide" },
      { q: "No of elevators", a: "4 nos Passenger, 1 service, 1 fire lift per tower and 2 shuttle elevators for parking areas" },
      { q: "whether the elevators will go to the terrace", a: "passenger elevators in the towers only" },
      { q: "If the elevators will not go to terrace then how ill the senior citizen having trouble in climbing reach the rooftop", a: "Not applicable" },
      { q: "Whether we are providing solar panels", a: "Yes" },
      { q: "Capacity of solar panels to generate electricity", a: "appx 125kw" },
      { q: "Placement of solar panels", a: "Above staircase top" },
      { q: "Provision of power backup", a: "DG Set and alternate power supply" },
      { q: "Position of generators", a: "on ground floor" },
      { q: "Brand of elevators", a: "not decided" },
      { q: "The service period of elevators", a: "as per vendor" },
      { q: "No of Servants toilets", a: "Servants toilet is planned on every midlanding of 1 staircase in both towers" },
      { q: "Service lift for carrying furniture and materials", a: "Yes" },
      { q: "No of refuge flats and its floors & the total area of refuge", a: "Refuge planned on every 7th Floor from 7th, 14th, 21st, 28th, 35th, 42nd" },
      { q: "Vermiculture", a: "no owc planned" },
      { q: "Rain water harvesting / STP", a: "Planned" },
      { q: "Borewell", a: "no" },
      { q: "No of charging points for EV vehicles and its positioning", a: "provision made" },
      { q: "Size and make of tiles for flooring", a: "kajaria/simpolo/rak/johnson or equivalent" },
      { q: "Size and make of tiles for bathroom, kitchen wall, bathroom walls", a: "kajaria/simpolo/rak/johnson or equivalent" },
      { q: "Height of dado tiles in the kitchen and washrooms", a: "Upto beam bottom" },
      { q: "Brand of sanitary and faucets", a: "toto/american standard or equivalent" },
      { q: "Warranty of faucets", a: "As per company" },
      { q: "Brand of switches, ELCB and MCB", a: "Projects team to provide" },
      { q: "Brand of electric wire and the size in MM for regular switches and for AC, Geyser etc", a: "Projects team to provide" },
      { q: "Position & number of switches and sockets", a: "Projects team to provide" },
      { q: "Provision for AC in the flat", a: "Yes" },
      { q: "Provision for keeping the outdoor units of AC", a: "Toilet ducts or ledges planned near utility" },
      { q: "Provision for drain pipe of AC so that it doesn't spoil the elevation and building colour", a: "Yes" },
      { q: "Size of windows in living area, bedrooms, kitchen and washrooms", a: "Living Room 2400 x 2300, Bedroom 1800 x 1950, Bathroom 600 x 900" },
      { q: "Provision for mosquito nets and if we are providing it", a: "no, not providing" },
      { q: "No of window tracks", a: "2 tracks" },
      { q: "Type of glass used in windows", a: "clear glass" },
      { q: "Size of Balcony/ deck", a: "in plan" },
      { q: "Whether we are providing safety railing", a: "In deck and utility" },
      { q: "Height of safety railing", a: "1.2m" },
      { q: "Type of paint used and its brand", a: "Projects team to provide" },
      { q: "Size of individual floor lobby", a: "2m wide" },
      { q: "Distance between the flats", a: "no" },
      { q: "Provision for sunlight and ventilation on the floors", a: "As per plan" },
      { q: "Whether the top floors will have separate line for water due to less pressure", a: "Telescopic plumbing" },
      { q: "The doors provided will be FRP or wooden", a: "Wooden" },
      { q: "Door frames wooden or marble", a: "bedrooms wooden, bathrooms will have granite" },
      { q: "Kitchen platform length and breadth", a: "as per plan" },
      { q: "Material of kitchen platform", a: "granite" },
      { q: "Size of kitchen sink", a: "18\"x24\"" },
      { q: "Whether washrooms will have concealed or open flush tanks", a: "Flush valves" },
      { q: "Whether the shower area will have a glass partition", a: "no" },
      { q: "Whether the shower area will have a water trap", a: "Yes" },
      { q: "Provision for Washing machine and fridge", a: "Yes" },
      { q: "Size & dimension of space for washing machine and fridge", a: "as per plan" },
      { q: "BMC and RERA carpet areas with dimension", a: "as per plan" },
      { q: "Whether the complex will have a single society or individual societies", a: "Legal Team" },
      { q: "Structure of residential", a: "Legal Team" },
      { q: "Structure of Retail", a: "Legal Team" },
      { q: "Total saleable area", a: "508353 sq ft" },
      { q: "Any certifications like IGBC", a: "Green building certified" },
      { q: "Source of electricity - TATA or Adani", a: "Projects team to provide" },
      { q: "Two phase or 3 phase wiring", a: "3 phase wiring" },
      { q: "CPVC or PVC pipes and company", a: "Projects team to provide" },
      { q: "Provision for Landline/internet/cable", a: "provision" },
      { q: "Are we providing lightning arrestor", a: "Yes" },
      { q: "Is the building earthquake resistant? If yes then its standard", a: "yes, zone 3" },
      { q: "Seismic zone of our project", a: "as per IS code 456" },
      { q: "Type of internal walls plaster (Cement/POP/Neru)", a: "gypsum plaster" },
      { q: "Provision for LV for fiber optics", a: "no" },
      { q: "Window frame whether it will be granite or marble", a: "marble" },
      { q: "Door frame whether it will be wood or marble", a: "Wood for room doors, granite for bathroom" },
      { q: "Door lock brand", a: "Godrej or equivalent" },
      { q: "Are all the apartments vastu compliance", a: "apartment entries are vastu compliant" },
      { q: "Vastu consultant name", a: "none" },
      { q: "Dry space/ balcony", a: "as per plan" },
      { q: "1st habitable floors starts and its height", a: "2nd floor 6.5m" },
      { q: "Power backup", a: "Yes" },
      { q: "Internal Road Size", a: "9m wide driveway" },
      { q: "Garbage chute", a: "no" },
      { q: "Fire chute", a: "no" },
      { q: "Exterior paint water repellent and its warranty", a: "acrylic Emulsion" },
      { q: "Are we giving loft in washroom", a: "no" },
      { q: "Provision for drying clothes", a: "Utility area" },
      { q: "Will there be marble or tiles in lobby", a: "Tile" },
      { q: "Will there be anti termite treatment inside the flats or just on the building", a: "Projects team to provide" },
      { q: "Incase of ramp for car parking, size of ramp", a: "6m wide 2 way ramp" },
      { q: "Density of the project i.e apartment to land area", a: "630 Apartments in 1 Acre" },
      { q: "What will be size of chajja", a: "min 300mm" },
      { q: "How deep will be the chajja from the slab", a: "550mm" },
      { q: "Floor to ceiling height and slab to slab height", a: "3m floor to floor" },
      { q: "Distance between 2 towers", a: "no" },
      { q: "Height of boundary wall between RG and residential", a: "5'" },
      { q: "How many staircase and width", a: "2 staircases with 2m width in each tower" },
      { q: "Water sprinklers whether it will be covered or not", a: "No" },
      { q: "Warranty for solar panels", a: "as per company" },
      { q: "Car washing area", a: "Parking areas" }
    ]
  }
};

// Format project data for AI context
export function getProjectDataPrompt(projectId = 'greenairy') {
  const project = PROJECTS[projectId] || PROJECTS['greenairy'];
  let prompt = `PROJECT DATA (STRICT - DO NOT HALLUCINATE OR INVENT ANY DATA):\n\n`;

  prompt += `Project: ${project.projectName}\n`;
  if (project.developer) prompt += `Developer: ${project.developer}\n`;
  if (project.location) prompt += `Location: ${project.location}\n`;

  if (project.basicDetails) {
    prompt += `\nBasic Details:\n`;
    project.basicDetails.forEach(d => prompt += `- ${d}\n`);
  }

  if (project.floorBands) {
    prompt += `\nFloor Bands & Rules:\n`;
    project.floorBands.forEach(f => prompt += `- ${f}\n`);
  }

  if (project.amenities) {
    prompt += `\nAmenities:\n`;
    for (const [category, items] of Object.entries(project.amenities)) {
      prompt += `- ${category}: ${items}\n`;
    }
  }

  if (project.configurations) {
    prompt += `\nAvailable Configurations:\n`;
    for (const [type, config] of Object.entries(project.configurations)) {
      prompt += `- ${type}: ${config.sizes.join(', ')} ${config.unit}\n`;
    }
  }

  if (project.wings) {
    prompt += `\nWings & Unit Inventory:\n`;
    for (const [wing, units] of Object.entries(project.wings)) {
      prompt += `- ${wing}:\n`;
      units.forEach(u => prompt += `  * ${u}\n`);
    }
  }

  prompt += `\nUSP (Unique Selling Points):\n`;
  project.usp.forEach(u => {
    prompt += `- ${u}\n`;
  });

  prompt += `\nCommon Customer Objections:\n`;
  project.commonObjections.forEach(o => {
    prompt += `- ${o}\n`;
  });

  if (project.faqs) {
    prompt += `\nFrequently Asked Questions (FAQs) [INTERNAL KNOWLEDGE ONLY - DO NOT ASK THESE DIRECTLY]:\n`;
    prompt += `IMPORTANT: The following FAQs are for your reference only. Use this information to evaluate the candidate's answers or to organically bring up topics if relevant to the conversation. DO NOT ask these questions verbatim to the candidate.\n\n`;
    project.faqs.forEach(faq => {
      prompt += `Q: ${faq.q}\nA: ${faq.a}\n\n`;
    });
  }

  return prompt;
}

// Persona definitions
export const PERSONAS = {
  'arrogant': {
    name: 'Arrogant',
    description: 'You are an arrogant, demanding customer who thinks they know everything about real estate. You dismiss the closing manager\'s points, constantly compare with competitors, and challenge pricing aggressively. You are hard to please and require strong, confident responses.',
    triggers: 'Use this persona when the candidate gives weak, vague, or incomplete answers.',
  },
  'confused': {
    name: 'Confused',
    description: 'You are a confused customer who doesn\'t understand real estate terminology well. You ask repeated clarifications, mix up configurations, and need patient, clear explanations. You often misunderstand what the closing manager says.',
    triggers: 'Use this persona when the candidate gives moderately good answers but needs to demonstrate patience and clarity.',
  },
  'easy-going': {
    name: 'Easy-going',
    description: 'You are a friendly, easy-going customer who is genuinely interested in the property. You ask reasonable questions and respond positively to good explanations. You are open to suggestions but still need convincing.',
    triggers: 'Use this persona when the candidate gives strong, confident, and complete answers.',
  },
};

export const EVALUATION_CRITERIA = {
  accuracy: {
    name: 'Accuracy',
    description: 'How accurately the candidate provided project information (sizes, configurations, USPs) without fabricating data.',
    weight: 20,
  },
  completeness: {
    name: 'Completeness',
    description: 'How thoroughly the candidate addressed all aspects of the customer\'s questions.',
    weight: 15,
  },
  objection_handling: {
    name: 'Objection Handling',
    description: 'How effectively the candidate handled customer objections, especially regarding pricing and competitor comparisons.',
    weight: 25,
  },
  clarity: {
    name: 'Clarity',
    description: 'How clearly and coherently the candidate communicated their points.',
    weight: 15,
  },
  confidence: {
    name: 'Confidence',
    description: 'How confident and assured the candidate sounded in their responses.',
    weight: 10,
  },
  sales_ability: {
    name: 'Sales Ability',
    description: 'Overall sales technique, persuasion skills, and ability to close the deal.',
    weight: 15,
  },
};
